//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptHash.Net.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptHash.Net.Resources.MessageStrings", typeof(MessageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm not supported:.
        /// </summary>
        internal static string Common_AlgorithmNotSupported {
            get {
                return ResourceManager.GetString("Common.AlgorithmNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found:.
        /// </summary>
        internal static string Common_FileNotFound {
            get {
                return ResourceManager.GetString("Common.FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorret hexadecimal string..
        /// </summary>
        internal static string Common_IncorrectHexadecimalString {
            get {
                return ResourceManager.GetString("Common.IncorrectHexadecimalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect data length, data probably tampered with..
        /// </summary>
        internal static string Common_IncorrectInputLengthError {
            get {
                return ResourceManager.GetString("Common.IncorrectInputLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags length must be equal..
        /// </summary>
        internal static string Common_IncorrectTagsLength {
            get {
                return ResourceManager.GetString("Common.IncorrectTagsLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid auth key bit size:.
        /// </summary>
        internal static string Common_InvalidAuthKeySizeError {
            get {
                return ResourceManager.GetString("Common.InvalidAuthKeySizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data length:.
        /// </summary>
        internal static string Common_InvalidDataLengthError {
            get {
                return ResourceManager.GetString("Common.InvalidDataLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid key bit size:.
        /// </summary>
        internal static string Common_InvalidKeySizeError {
            get {
                return ResourceManager.GetString("Common.InvalidKeySizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication for decryption failed, wrong password or data probably tampered with..
        /// </summary>
        internal static string Decryption_AuthenticationTagsMismatchError {
            get {
                return ResourceManager.GetString("Decryption.AuthenticationTagsMismatchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypted file path required..
        /// </summary>
        internal static string Decryption_DecryptedFilePathError {
            get {
                return ResourceManager.GetString("Decryption.DecryptedFilePathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data succesfully decrypted..
        /// </summary>
        internal static string Decryption_DecryptSuccess {
            get {
                return ResourceManager.GetString("Decryption.DecryptSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted file not found:.
        /// </summary>
        internal static string Decryption_EncryptedFileNotFound {
            get {
                return ResourceManager.GetString("Decryption.EncryptedFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End position (\&quot;{0}\&quot;) cannot be less than start position (\&quot;{1}\&quot;)..
        /// </summary>
        internal static string Decryption_EndPositionLessThanStartError {
            get {
                return ResourceManager.GetString("Decryption.EndPositionLessThanStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to decrypt data:.
        /// </summary>
        internal static string Decryption_ExceptionError {
            get {
                return ResourceManager.GetString("Decryption.ExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File \&quot;{0}\&quot; successfully decrypted to \&quot;{1}\&quot;..
        /// </summary>
        internal static string Decryption_FileDecryptSuccess {
            get {
                return ResourceManager.GetString("Decryption.FileDecryptSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input to decrypt required..
        /// </summary>
        internal static string Decryption_InputRequired {
            get {
                return ResourceManager.GetString("Decryption.InputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. encrypted input size cannot be greater in bytes than:.
        /// </summary>
        internal static string Decryption_MaxEncryptedInputSizeError {
            get {
                return ResourceManager.GetString("Decryption.MaxEncryptedInputSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IV cannot be null..
        /// </summary>
        internal static string Decryption_NullIVError {
            get {
                return ResourceManager.GetString("Decryption.NullIVError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key cannot be null..
        /// </summary>
        internal static string Decryption_NullKeyError {
            get {
                return ResourceManager.GetString("Decryption.NullKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password to decrypt required..
        /// </summary>
        internal static string Decryption_PasswordRequired {
            get {
                return ResourceManager.GetString("Decryption.PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination directory not found:.
        /// </summary>
        internal static string Encryption_DestinationDirectoryNotFound {
            get {
                return ResourceManager.GetString("Encryption.DestinationDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted file path required..
        /// </summary>
        internal static string Encryption_EncryptedFilePathError {
            get {
                return ResourceManager.GetString("Encryption.EncryptedFilePathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data succesfully encrypted..
        /// </summary>
        internal static string Encryption_EncryptSuccess {
            get {
                return ResourceManager.GetString("Encryption.EncryptSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while trying to encrypt data:.
        /// </summary>
        internal static string Encryption_ExceptionError {
            get {
                return ResourceManager.GetString("Encryption.ExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing additional data to file....
        /// </summary>
        internal static string Encryption_FileAdditionalDataWriting {
            get {
                return ResourceManager.GetString("Encryption.FileAdditionalDataWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional data written to file..
        /// </summary>
        internal static string Encryption_FileAdditionalDataWritten {
            get {
                return ResourceManager.GetString("Encryption.FileAdditionalDataWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File \&quot;{0}\&quot; deleted..
        /// </summary>
        internal static string Encryption_FileDeleted {
            get {
                return ResourceManager.GetString("Encryption.FileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File \&quot;{0}\&quot; successfully encrypted to \&quot;{1}\&quot;..
        /// </summary>
        internal static string Encryption_FileEncryptSuccess {
            get {
                return ResourceManager.GetString("Encryption.FileEncryptSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input to encrypt required..
        /// </summary>
        internal static string Encryption_InputRequired {
            get {
                return ResourceManager.GetString("Encryption.InputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. associated data size cannot be greater in bytes than:.
        /// </summary>
        internal static string Encryption_MaxAssociatedDataSizeError {
            get {
                return ResourceManager.GetString("Encryption.MaxAssociatedDataSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. input size cannot be greater in bytes than:.
        /// </summary>
        internal static string Encryption_MaxInputSizeError {
            get {
                return ResourceManager.GetString("Encryption.MaxInputSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password to encrypt required..
        /// </summary>
        internal static string Encryption_PasswordRequired {
            get {
                return ResourceManager.GetString("Encryption.PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input hash computed succesfully..
        /// </summary>
        internal static string Hash_ComputeSuccess {
            get {
                return ResourceManager.GetString("Hash.ComputeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input hash and verification hash does not match..
        /// </summary>
        internal static string Hash_DoesNotMatch {
            get {
                return ResourceManager.GetString("Hash.DoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input to compute hash required..
        /// </summary>
        internal static string Hash_InputRequired {
            get {
                return ResourceManager.GetString("Hash.InputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input hash and verification hash match..
        /// </summary>
        internal static string Hash_Match {
            get {
                return ResourceManager.GetString("Hash.Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification hash required..
        /// </summary>
        internal static string Hash_VerificationHashRequired {
            get {
                return ResourceManager.GetString("Hash.VerificationHashRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input HMAC computed succesfully..
        /// </summary>
        internal static string HMAC_ComputeSuccess {
            get {
                return ResourceManager.GetString("HMAC.ComputeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input to compute HMAC required..
        /// </summary>
        internal static string HMAC_InputRequired {
            get {
                return ResourceManager.GetString("HMAC.InputRequired", resourceCulture);
            }
        }
    }
}
