name: build-and-test
on: 
    push:
        branches:
            - develop
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    - name: Build
      run: dotnet build --configuration Release src/CryptHash.Net/lib/CryptHash.Net/CryptHash.Net.csproj

    - name: Run tests
      run: dotnet test src/CryptHash.Net/lib/CryptHash.Net.Tests/CryptHash.Net.Tests.csproj
